Added Presentation material for WiSe 2021
mas-group/foundations_course pull request #81
Opened 2021-09-27 07:38 UTC by MihirMehta5695

Added & updated Presentation slides for 'Algorithm Analysis & Data Structures' and 'Introduction to Machine Learning' sessions.

2021-09-27 08:11 UTC, alex-mitrevski requested changes
A few minor language fixes in the ML slides:
* in the definition of ML on slide 8, there shouldn't be spaces before the commas
* on slide 9, v/s should be vs
* on slide 13, don't capitalise "algorithms" in the box titles
* on slide 15, add a space before the parentheses in the box on the right
* on slides 18-20, both messages seem like spam to me; I would look for a better ham example (but if the example is taken from [9], keep it)
* Be consistent with the spelling of labelling (you have labeling in some places)

For this PR, I will ignore two things, but we should change them in future:
* On all slides, there's too much caplitalisation where it doesn't belong.
* I would prefer the references to be footnotes on the slides where they are needed rather than appear at the end.

2022-03-17 23:25 UTC, MihirMehta5695 commented
> A few minor language fixes in the ML slides:
> 
>     * in the definition of ML on slide 8, there shouldn't be spaces before the commas
> 
>     * on slide 9, v/s should be vs
> 
>     * on slide 13, don't capitalise "algorithms" in the box titles
> 
>     * on slide 15, add a space before the parentheses in the box on the right
> 
>     * on slides 18-20, both messages seem like spam to me; I would look for a better ham example (but if the example is taken from [9], keep it)
> 
>     * Be consistent with the spelling of labelling (you have labeling in some places)
> 
> 
> For this PR, I will ignore two things, but we should change them in future:
> 
>     * On all slides, there's too much caplitalisation where it doesn't belong.
> 
>     * I would prefer the references to be footnotes on the slides where they are needed rather than appear at the end.

Updated according to the changes

2022-03-19 17:57 UTC, alex-mitrevski approved these changes

2022-03-19 17:57 UTC, merged

2022-03-19 17:58 UTC, alex-mitrevski commented
Thanks @MihirMehta5695!